config:
  connection:
    type: TLSPC
    credentials:
      apikey: foobar123
certificateTasks:
  - name: mtls
    request:
      zone: "Open Source\\vcert"
      subject:
        commonName: '{{ NonExist | ToLower -}}.{{- Env "USERDNSDOMAIN" | ToLower }}'
        country: US
        locality: Salt Lake City
        province: Utah
        organization: Venafi Inc
        orgUnits:
          - engineering
          - marketing
      csrOrigin: service
      keyPassword: "CyberArkT3stP4ZZC0de%jQX^J=4H"
    installations:
      - type: JKS
        location: "/Users/rvela/venafi/supertreat/jks/foo.jks"
        afterInstallAction: "sh -c 'mySweetScrip.sh'"
        jksAlias: "kwan"
        jksPassword: "foobar123"
    renewBefore: 31d