config:
  connection:
    type: TPP
    credentials:
      accessToken: '{{ Env "TPP_ACCESS_TOKEN" }}'
      refreshToken: '{{ Env "TPP_REFRESH_TOKEN" }}'
    trustBundle: /Users/rvela/venafi/supertreat/bundle.cer
    url: https://supertreat.venqa.venafi.com
certificateTasks:
  - name: mtls
    request:
      zone: "Open Source\\vcert"
      subject:
        commonName: foo.bar.venafi.com
        country: US
        locality: Salt Lake City
        province: Utah
        organization: Venafi Inc
        orgUnits:
          - engineering
          - marketing
      csrOrigin: service
      keyPassword: "Passcode123!"
    installations:
      - type: PEM
        location: "/Users/rvela/venafi/supertreat/pem"
        afterInstallAction: "echo Success!!!"
    renewBefore: 31d